---
- name: Configure SE-Group
  community.network.avi_serviceenginegroup:
    avi_credentials: "{{ avi_credentials }}"
    tenant: "{{ tenant_name }}"
    name: "{{ se_group_name }}"
    state: "{{ state }}"
    cloud_ref: "/api/cloud?name={{ cloud_name }}"
    ha_mode: "{{ ha_mode }}"
    min_scaleout_per_vs: "{{ min_scaleout_per_vs }}"
    buffer_se: "{{ buffer_se }}"
    max_se: "{{ max_se }}"
    se_name_prefix: "{{ se_name_prefix }}"
    vcenter_folder: "{{ vcenter_folder }}"
    vcpus_per_se: "{{ vcpus_per_se }}"
    memory_per_se: "{{ memory_per_se }}"
    disk_per_se: "{{ disk_per_se }}"
    cpu_reserve: "{{ cpu_reserve }}"
    mem_reserve: "{{ mem_reserve }}"
  register: service_engine_group
 

# - name: Print return information from the previous task
#   ansible.builtin.debug:
#     var: service_engine_group

# - name: Update Cloud Configuration with Mgmt Network 
#   avi_cloud:
#     avi_credentials: "{{ avi_credentials }}"
#     avi_api_update_method: "{{ avi_api_update_method }}"
#     avi_api_patch_op: "{{ avi_api_patch_op }}"
#     name: "{{ cloud_name }}"
#     se_group_template_ref: "https://10.100.147.10/api/serviceenginegroup/serviceenginegroup-0ca4c3c2-3cd6-43bc-ba06-df52657e83f4#Default-Group"
#     vtype: "{{ cloud_type }}"